### ISSUE TITLE
Non - ROS Version for Mars Logger

### ISSUE THREAD

**Issue by qamaruislam** [OSUPCVLab/mobile-ar-sensor-logger#16]
Dear @JzHuai0108 

Thank you for your contribution. Is there any way to run data with mars logger without using BAG File for NON ROS version of ORB-SLAM3? It seems here (https://github.com/OSUPCVLab/mobile-ar-sensor-logger) only explains how to run the sequence with a bag file for the ROS version of ORB SLAM3. ****How to modify the dataset file from Mars Logger to run sequences in TUM-VI or EuRoC Dataset Format?****

Any suggestions and recommendations are highly appreciated.

Thank you.

**Comment by JzHuai0108** [comment]
Thank you for using the logger.

I actually have written such code to interface a VIO or VI SLAM method with the datasets recorded by the MARS logger.
But these codes are clumsy and unwieldy and I recently do not have much time to clean up and publish them.

When the MARS logger was developed, we tried to keep its data file format close to the [Kalibr format](https://github.com/ethz-asl/kalibr/wiki/bag-format).
This format is very similar to EuRoC, and also close to TUM-VI format.

Overall, my experience is that it is fairly easy to run ORB-SLAM3 by reading directly data logged by MARS logger.
You can see the classes, FrameGrabber, TimeGrabber, and ImuGrabber at [here](https://github.com/JzHuai0108/vio_common/tree/master/src).
I have been using these classes to load the MARS logger data in real time.
Hope this can get you started.
