### ISSUE TITLE
about the sampling frequency of IMU

### ISSUE THREAD

**Issue by zzbwhu** [OSUPCVLab/mobile-ar-sensor-logger#2]
Dear Huai:
    Thanks for your work, very great!
    There i have two questions:
   1: in the class of IMUManager, the sampling frequency of acc and gyro are setted as  SENSOR_DELAY_GAME, such as
        private final int mSensorRate = SensorManager.SENSOR_DELAY_GAME; 
      while    SENSOR_DELAY_GAME represents the delay time is 20000  
![Uploading image.png…]()
which means the sampling frequency should be 50hz , while the logged data of acc and gyro are 100 hz , it is contradictory
2: when i add a sensor: 
mMag = mSensorManager.getDefaultSensor(Sensor.TYPE_MAGNETIC_FIELD);    in the function IMUmanager just follow the 
mGyro = mSensorManager.getDefaultSensor(Sensor.TYPE_GYROSCOPE);
then the sampling frequency of mag is 50 Hz , while the acc and gyro are still 100hz , so how to change the sampling frequency of mag into 100 hz , is there some thing i missing?

**Comment by JzHuai0108** [comment]
I think you are doing all right. 
The nuance likely comes from your android phone. 
Though you specified the sensor sampling frequency, the actual sensor and application can use a different one.
More info at [here](https://stackoverflow.com/questions/11685400/sensor-delay-game-how-much-is-it).
