### ISSUE TITLE
NullPointerException even after editing build.gradle

### ISSUE THREAD

**Issue by jxu12345** [OSUPCVLab/mobile-ar-sensor-logger#22]
Hi Josh,

I read the issue on the null pointer exception and attempted the easy fix, deleting all references to the signing config. However, I'm still getting a nullPointerException, except this time with no error message.

These are the edits I made. Please check that I'm doing them correctly.
![image](https://user-images.githubusercontent.com/43282957/143669275-c54db6e5-6dd5-4167-bc4d-5b495d1ce21e.png)

This is the error message I get. 
![image](https://user-images.githubusercontent.com/43282957/143669289-7a830f2c-cbb0-4b48-b776-80a3f45e1f14.png)

Thanks,
Jason

**Comment by JzHuai0108** [comment]
I recall there was some line in the code causing the problem, and I fixed these issues a while ago.
This repo currently has two apps, one for iOS, one for android. It is very inconvenient for pull requests.
I am thinking to split it into two. I will do this in a couple of days. 
Meanwhile, you may try the bitbucket repo for [android MARS logger](https://bitbucket.org/JzHuai0108/mars_logger_android).
The master branch has been built and tested in Android studio 2020.

**Comment by jxu12345** [comment]
Thank you very much! The code from bitbucket works without problem.
