### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: path may not be null or empty string. path='null'

### ISSUE THREAD

**Issue by sarimmehdi** [OSUPCVLab/mobile-ar-sensor-logger#24]
I am unable to open your project in android studio as I get this error.

**Comment by sarimmehdi** [comment]
The problem was solved by removing the following lines from build.gradle:

```
signingConfigs {
        release {
            Properties properties = new Properties()
            properties.load(project.rootProject.file('local.properties').newDataInputStream())
            storeFile file(properties.getProperty('storeFile'))
            keyAlias properties.getProperty('keyAlias')
            storePassword properties.getProperty('storePassword')
            keyPassword properties.getProperty('keyPassword')
        }
    }
```
and then removing this line from the `release` braces of `buildTypes`:

`signingConfig signingConfigs.release`

**Comment by JzHuai0108** [comment]
Good job. Actually, these lines are related to building the release version which requires your own keystore and key. You know I can't share them with you :). The shortcut is simply to comment out the release build options or to use the debug version.
