### ISSUE TITLE
record game rotation vector

### ISSUE THREAD

**Issue by CanCanZeng** [OSUPCVLab/mobile-ar-sensor-logger#33]
Hi, thank you for sharing this tool!
I compiled android version successfully and it worked well. But I'm not familiar with android coding, how can I record game rotation vector at the same time? Can you add this sensor or give me some instruction?

**Comment by JzHuai0108** [comment]
A while ago, someone wanted to record the magnetometer data, and I added this feature as done [in this commit](https://github.com/OSUPCVLab/marslogger_android/compare/main...develop).
It should be quite similar to recording the [game rotation vector](https://developer.android.com/guide/topics/sensors/sensors_position#sensors-pos-gamerot) following the android doc.
You already had a good start by succeeding in compiling the mars logger.

**Comment by CanCanZeng** [comment]
Thank you for your answer, I will try it later.
