### ISSUE TITLE
Can not find the record file

### ISSUE THREAD

**Issue by elevenjiang1** [OSUPCVLab/mobile-ar-sensor-logger#34]
Hello, thanks for your work!
However, I am using Xiaomi 14, but I can not find output file in /Android/data, and My phone has no sdcard, so, where may it be output?

**Comment by JzHuai0108** [comment]
I recall the logger reports the output path in some screen. Do you notice it?

**Comment by elevenjiang1** [comment]
Yes, I see the output folder, but I still can not search it out

![img_v3_0288_57453e53-14de-4c17-b83c-dad3a7a1b67g](https://github.com/OSUPCVLab/mobile-ar-sensor-logger/assets/43636049/c6675453-3cad-4976-a4f8-43a24ba4a84a)

**Comment by JzHuai0108** [comment]
Do you see the edu.osu.pcv folder on your phone, as shown below?

![screen](https://github.com/OSUPCVLab/mobile-ar-sensor-logger/assets/8062561/2786bb51-0865-433c-8273-47f602bcfe73)

Have you granted the storage permission to the app?

**Comment by JzHuai0108** [comment]
![Uploading screen.jpg…](This is the sample screen).

**Comment by elevenjiang1** [comment]
Maybe because Xiaomi do not give the root permission to /Andriod/data, some links found like: 
https://web.vip.miui.com/page/info/mio/mio/detail?app_version=dev.20051&postId=37583191

I have chosen another open source projcet: https://github.com/MobileRoboticsSkoltech/OpenCamera-Sensors?tab=readme-ov-file, and it saves the data to "DCIM/OpenCamera" path, so that I can find the data.

But still thanks a lot for your help~~
By the way, I also graduate from WHU~~~

**Comment by JzHuai0108** [comment]
Oddly, my Redmi K40 Pro can run the app without any issue. 

That one looks good to me. I have read through the open camera code base before, but this app is new to me.
Thanks for letting me know :).
